local LSM = LibStub("LibSharedMedia-3.0")

-- register sounds
LSM:Register("sound", "|cff0091ed1 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\1 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed2 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\2 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed3 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\3 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed4 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\4 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed5 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\5 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed6 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\6 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed7 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\7 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed8 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\8 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed9 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\9 -Naowh.ogg")
LSM:Register("sound", "|cff0091ed10 -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\10 -Naowh.ogg")
LSM:Register("sound", "|cff0091edAdd -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Add -Naowh.ogg")
LSM:Register("sound", "|cff0091edAdds -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Adds -Naowh.ogg")
LSM:Register("sound", "|cff0091edAoE -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\AoE -Naowh.ogg")
LSM:Register("sound", "|cff0091edAvoid -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Avoid -Naowh.ogg")
LSM:Register("sound", "|cff0091edBait -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Bait -Naowh.ogg")
LSM:Register("sound", "|cff0091edBehind -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Behind -Naowh.ogg")
LSM:Register("sound", "|cff0091edBloodlust -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Bloodlust -Naowh.ogg")
LSM:Register("sound", "|cff0091edBuff -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Buff -Naowh.ogg")
LSM:Register("sound", "|cff0091edCC -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\CC -Naowh.ogg")
LSM:Register("sound", "|cff0091edClear In -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Clear In -Naowh.ogg")
LSM:Register("sound", "|cff0091edClear -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Clear -Naowh.ogg")
LSM:Register("sound", "|cff0091edCollect -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Collect -Naowh.ogg")
LSM:Register("sound", "|cff0091edCombat -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Combat -Naowh.ogg")
LSM:Register("sound", "|cff0091edDance -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Dance -Naowh.ogg")
LSM:Register("sound", "|cff0091edDebuff -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Debuff -Naowh.ogg")
LSM:Register("sound", "|cff0091edDispell -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Dispell -Naowh.ogg")
LSM:Register("sound", "|cff0091edDodge Inc -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Dodge Inc -Naowh.ogg")
LSM:Register("sound", "|cff0091edDodge -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Dodge -Naowh.ogg")
LSM:Register("sound", "|cff0091edDot -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Dot -Naowh.ogg")
LSM:Register("sound", "|cff0091edFixate -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Fixate -Naowh.ogg")
LSM:Register("sound", "|cff0091edFrontal -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Frontal -Naowh.ogg")
LSM:Register("sound", "|cff0091edHide -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Hide -Naowh.ogg")
LSM:Register("sound", "|cff0091edHigh Stacks -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\High Stacks -Naowh.ogg")
LSM:Register("sound", "|cff0091edImmune -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Immune -Naowh.ogg")
LSM:Register("sound", "|cff0091edIn -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\In -Naowh.ogg")
LSM:Register("sound", "|cff0091edInc -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Inc -Naowh.ogg")
LSM:Register("sound", "|cff0091edInside -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Inside -Naowh.ogg")
LSM:Register("sound", "|cff0091edIntermission -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Intermission -Naowh.ogg")
LSM:Register("sound", "|cff0091edKick -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Kick -Naowh.ogg")
LSM:Register("sound", "|cff0091edKnock -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Knock -Naowh.ogg")
LSM:Register("sound", "|cff0091edLeft -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Left -Naowh.ogg")
LSM:Register("sound", "|cff0091edLinked -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Linked -Naowh.ogg")
LSM:Register("sound", "|cff0091edLoS -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\LoS -Naowh.ogg")
LSM:Register("sound", "|cff0091edLostVikings -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\LongboatRaid.ogg")
LSM:Register("sound", "|cff0091edLorgok Boss Dmg -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_BossDmg.ogg")
LSM:Register("sound", "|cff0091edLorgok Burp -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_Burp.ogg")
LSM:Register("sound", "|cff0091edLorgok Doesnt Happen -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_DoesntHappen.ogg")
LSM:Register("sound", "|cff0091edLorgok Ejaculate -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_Ejaculate.ogg")
LSM:Register("sound", "|cff0091edLorgok Help -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_Help.ogg")
LSM:Register("sound", "|cff0091edLorgok Noooo -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_Noooo.ogg")
LSM:Register("sound", "|cff0091edLorgok Oh What -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_OhWhat.ogg")
LSM:Register("sound", "|cff0091edLorgok Ok Bro -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_OkBro.ogg")
LSM:Register("sound", "|cff0091edLorgok Oribole -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_Oribole.ogg")
LSM:Register("sound", "|cff0091edLorgok Stupid Dude -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_StupidDude.ogg")
LSM:Register("sound", "|cff0091edLorgok WTF -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_WTF.ogg")
LSM:Register("sound", "|cff0091edLorgok Yeah -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_Yeah.ogg")
LSM:Register("sound", "|cff0091edLorgok Boss Dmg -Naowh|r", "Interface\\AddOns\\SharedMedia_Julsanity\\Sounds\\Lorgok_BossDmg.ogg")

-- register options font
LSM:Register("font", "Accidental Presidency", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Accidental_Presidency.ttf")
LSM:Register("font", "Adventure", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Adventure.ttf")
LSM:Register("font", "All Hooked Up", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\HookedUp.ttf")
LSM:Register("font", "Bazooka", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Bazooka.ttf")
LSM:Register("font", "Black Chancery", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\BlackChancery.ttf")
LSM:Register("font", "Celestia Medium Redux", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\CelestiaMediumRedux1.55.ttf")
LSM:Register("font", "DejaVu Sans", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\DejaVuLGCSans.ttf",   LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "DejaVu Serif", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\DejaVuLGCSerif.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "DorisPP", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\DorisPP.ttf")
LSM:Register("font", "Enigmatic", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\EnigmaU_2.ttf")
LSM:Register("font", "Fitzgerald", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Fitzgerald.ttf")
LSM:Register("font", "Gentium Plus", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\GentiumPlus-R.ttf",  LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "Hack", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Hack-Regular.ttf")
LSM:Register("font", "Liberation Sans", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\LiberationSans-Regular.ttf",  LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "Liberation Serif", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\LiberationSerif-Regular.ttf",    LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "SF Atarian System", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\SFAtarianSystem.ttf")
LSM:Register("font", "SF Covington", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\SFCovington.ttf")
LSM:Register("font", "SF Movie Poster", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\SFMoviePoster-Bold.ttf")
LSM:Register("font", "SF Wonder Comic", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\SFWonderComic.ttf")
LSM:Register("font", "swf!t", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\SWF!T___.ttf")
LSM:Register("font", "WenQuanYi Zen Hei", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\wqy-zenhei.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU + LSM.LOCALE_BIT_koKR + LSM.LOCALE_BIT_zhCN + LSM.LOCALE_BIT_zhTW)
LSM:Register("font", "Yellowjacket", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\yellow.ttf")
LSM:Register("font", "Naowh", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Naowh.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "GothamNarrowUltra", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\GothamNarrowUltra.ttf", LSM.LOCALE_BIT_western + LSM.LOCALE_BIT_ruRU)
LSM:Register("font", "Raleway Regular", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Raleway-Regular.ttf")
LSM:Register("font", "Raleway Medium", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Raleway-Medium.ttf")
LSM:Register("font", "Raleway SemiBold", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Raleway-SemiBold.ttf")
LSM:Register("font", "Cell Han Sans SC", "Interface\\AddOns\\SharedMedia_Julsanity\\Fonts\\Cell_HanSans_SC.ttf")


-- register plain white border
LSM:Register("statusbar", "Aluminium", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Aluminium]])
LSM:Register("statusbar", "Armory", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Armory]])
LSM:Register("statusbar", "BantoBar", [[Interface\AddOns\SharedMedia_Julsanity\Textures\BantoBar]])
LSM:Register("statusbar", "Bars", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Bars]])
LSM:Register("statusbar", "Bumps", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Bumps]])
LSM:Register("statusbar", "Button", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Button]])
LSM:Register("statusbar", "Charcoal", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Charcoal]])
LSM:Register("statusbar", "Cilo", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Cilo]])
LSM:Register("statusbar", "Cloud", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Cloud]])
LSM:Register("statusbar", "Comet", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Comet]])
LSM:Register("statusbar", "Dabs", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Dabs]])
LSM:Register("statusbar", "DarkBottom", [[Interface\AddOns\SharedMedia_Julsanity\Textures\DarkBottom]])
LSM:Register("statusbar", "Diagonal", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Diagonal]])
LSM:Register("statusbar", "Empty", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Empty]])
LSM:Register("statusbar", "Falumn", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Falumn]])
LSM:Register("statusbar", "Fifths", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Fifths]])
LSM:Register("statusbar", "Flat", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Flat]])
LSM:Register("statusbar", "Fourths", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Fourths]])
LSM:Register("statusbar", "Frost", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Frost]])
LSM:Register("statusbar", "Glamour", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour]])
LSM:Register("statusbar", "Glamour2", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour2]])
LSM:Register("statusbar", "Glamour3", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour3]])
LSM:Register("statusbar", "Glamour4", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour4]])
LSM:Register("statusbar", "Glamour5", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour5]])
LSM:Register("statusbar", "Glamour6", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour6]])
LSM:Register("statusbar", "Glamour7", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glamour7]])
LSM:Register("statusbar", "Glass", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glass]])
LSM:Register("statusbar", "Glaze", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glaze]])
LSM:Register("statusbar", "Glaze v2", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Glaze2]])
LSM:Register("statusbar", "Gloss", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Gloss]])
LSM:Register("statusbar", "Graphite", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Graphite]])
LSM:Register("statusbar", "Grid", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Grid]])
LSM:Register("statusbar", "Hatched", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Hatched]])
LSM:Register("statusbar", "Healbot", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Healbot]])
LSM:Register("statusbar", "Lyfe", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Lyfe]])
LSM:Register("statusbar", "LiteStep", [[Interface\AddOns\SharedMedia_Julsanity\Textures\LiteStep]])
LSM:Register("statusbar", "LiteStepLite", [[Interface\AddOns\SharedMedia_Julsanity\Textures\LiteStepLite]])
LSM:Register("statusbar", "Melli", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Melli]])
LSM:Register("statusbar", "Melli Dark", [[Interface\AddOns\SharedMedia_Julsanity\Textures\MelliDark]])
LSM:Register("statusbar", "Melli Dark Rough", [[Interface\AddOns\SharedMedia_Julsanity\Textures\MelliDarkRough]])
LSM:Register("statusbar", "Minimalist", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Minimalist]])
LSM:Register("statusbar", "Otravi", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Otravi]])
LSM:Register("statusbar", "Outline", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Outline]])
LSM:Register("statusbar", "Perl", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Perl]])
LSM:Register("statusbar", "Perl v2", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Perl2]])
LSM:Register("statusbar", "Pill", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Pill]])
LSM:Register("statusbar", "Rain", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Rain]])
LSM:Register("statusbar", "Rocks", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Rocks]])
LSM:Register("statusbar", "Round", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Round]])
LSM:Register("statusbar", "Ruben", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Ruben]])
LSM:Register("statusbar", "Runes", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Runes]])
LSM:Register("statusbar", "Skewed", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Skewed]])
LSM:Register("statusbar", "Smooth", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Smooth]])
LSM:Register("statusbar", "Smooth v2", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Smoothv2]])
LSM:Register("statusbar", "Smudge", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Smudge]])
LSM:Register("statusbar", "Steel", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Steel]])
LSM:Register("statusbar", "Striped", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Striped]])
LSM:Register("statusbar", "Tube", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Tube]])
LSM:Register("statusbar", "Water", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Water]])
LSM:Register("statusbar", "Wglass", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Wglass]])
LSM:Register("statusbar", "Wisps", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Wisps]])
LSM:Register("statusbar", "Xeon", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Xeon]])
LSM:Register("statusbar", "Statusbar", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Statusbar]])
LSM:Register("statusbar", "White", [[Interface\AddOns\SharedMedia_Julsanity\Textures\White]])
LSM:Register("statusbar", "Shield", [[Interface\AddOns\SharedMedia_Julsanity\Textures\Shield]])